pbctf/2021/web/mail_tester/config/routes.rb
Rails.application.routes.draw do
  root "login#index"
  post 'login', to: "login#create"

  get 'email', to: "email#index"
  post 'email', to: "email#create"
end

pbctf/2021/web/mail_tester/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

pbctf/2021/web/mail_tester/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :require_authenticated

    def logged_in?
        session[:user_id].present?
    end

    def require_authenticated
       render status: 401, plain: "Unauthenticated" unless logged_in?
    end
end

pbctf/2021/web/mail_tester/app/controllers/email_controller.rb
class EmailController < ApplicationController
  def index; end

  def create
    if email_params[:to] && email_params[:message]
      send_mail
      flash[:notice] = 'Email has been sent'
    else
      flash[:notice] = 'Must supply and address and a message'
    end

    redirect_to email_url
  end

  def email_params
    params.permit(:to, :message)
  end

  private

  def send_mail
    IO.popen("/usr/sbin/sendmail -B 7BIT -i -f app@localhost -- #{quoted_to}", 'w+', err: :out) do |io|
      io.puts email_params[:message]
      io.flush
    end
  end

  def quoted_to
    %("#{email_params[:to].shellescape}")
  end
end

pbctf/2021/web/mail_tester/app/controllers/login_controller.rb
require 'digest'

class LoginController < ApplicationController
  skip_before_action :require_authenticated

  def index
    redirect_to email_url if logged_in?
  end

  def create
    render status: 422, plain: "username is required" unless login_params[:username].present?
    session[:user_id] = Digest::MD5.hexdigest(login_params[:username] + login_params[:password])
    redirect_to email_url
  end

  def login_params
    params.permit(:username, :password)
  end

end

pbctf/2021/web/mail_tester/app/helpers/application_helper.rb
module ApplicationHelper
end

pbctf/2021/web/mail_tester/app/helpers/email_helper.rb
module EmailHelper
end

pbctf/2021/web/mail_tester/app/helpers/login_helper.rb
module LoginHelper
end

pbctf/2021/web/mail_tester/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mail Tester</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

pbctf/2021/web/mail_tester/app/views/login/index.html.erb
<h1>Login</h1>

<%= form_with url: login_url, method: :post do |form| %>
  <%= form.label :username, "Username" %>
  <%= form.text_field :username %>

  <%= form.label :password, "Password" %>
  <%= form.password_field :password %>

  <%= form.submit "Login" %>
<% end %>